In [1]:
import numpy as np

In [13]:
arr = np.array([[2,-2,1], [-4,-8,-8]])
U, S, VT = np.linalg.svd(arr)

In [14]:
# Left singular vectors
U

array([[ 9.86864911e-18,  1.00000000e+00],
       [ 1.00000000e+00, -9.86864911e-18]])

In [15]:
# Singular values
S

array([12.,  3.])

In [16]:
# Right singular vectors
VT

array([[-0.33333333, -0.66666667, -0.66666667],
       [ 0.66666667, -0.66666667,  0.33333333],
       [-0.66666667, -0.33333333,  0.66666667]])